spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vaistra-blog-app
    username: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL8Dialect


SERVER_PORT: 8080

#EMAIL CONFIG
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: nadeempalkhiwala9@gmail.com
EMAIL_PASSWORD: akxotpqucexvsflw
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}